//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_ManipulationSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean vanish
        {
            get
            {
                return SteamVR_Actions.manipulationSet_vanish;
            }
        }
        
        public virtual SteamVR_Action_Vector2 change_size
        {
            get
            {
                return SteamVR_Actions.manipulationSet_change_size;
            }
        }
        
        public virtual SteamVR_Action_Boolean red
        {
            get
            {
                return SteamVR_Actions.manipulationSet_red;
            }
        }
        
        public virtual SteamVR_Action_Boolean blue
        {
            get
            {
                return SteamVR_Actions.manipulationSet_blue;
            }
        }
        
        public virtual SteamVR_Action_Boolean green
        {
            get
            {
                return SteamVR_Actions.manipulationSet_green;
            }
        }
        
        public virtual SteamVR_Action_Boolean yellow
        {
            get
            {
                return SteamVR_Actions.manipulationSet_yellow;
            }
        }
        
        public virtual SteamVR_Action_Boolean change_position
        {
            get
            {
                return SteamVR_Actions.manipulationSet_change_position;
            }
        }
    }
}
