//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_MasterarbeitSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean switch_scene
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_switch_scene;
            }
        }
        
        public virtual SteamVR_Action_Boolean Interact_UI
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_Interact_UI;
            }
        }
        
        public virtual SteamVR_Action_Boolean vanish
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_vanish;
            }
        }
        
        public virtual SteamVR_Action_Boolean change_position
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_change_position;
            }
        }
        
        public virtual SteamVR_Action_Vector2 change_size
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_change_size;
            }
        }
        
        public virtual SteamVR_Action_Boolean speed_booster
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_speed_booster;
            }
        }
        
        public virtual SteamVR_Action_Boolean start_walking
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_start_walking;
            }
        }
        
        public virtual SteamVR_Action_Vector2 walk_direction
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_walk_direction;
            }
        }
        
        public virtual SteamVR_Action_Boolean red
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_red;
            }
        }
        
        public virtual SteamVR_Action_Boolean blue
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_blue;
            }
        }
        
        public virtual SteamVR_Action_Boolean yellow
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_yellow;
            }
        }
        
        public virtual SteamVR_Action_Boolean green
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_green;
            }
        }
        
        public virtual SteamVR_Action_Boolean white
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_white;
            }
        }
        
        public virtual SteamVR_Action_Boolean start_change_size
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_start_change_size;
            }
        }
        
        public virtual SteamVR_Action_Boolean stop_change_size
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_stop_change_size;
            }
        }
        
        public virtual SteamVR_Action_Boolean select_object
        {
            get
            {
                return SteamVR_Actions.masterarbeitSet_select_object;
            }
        }
    }
}
